#!/usr/bin/env sh

ARGS=("$@")

ENV_PATH='env'
GOOGLE_SERVICES_ANDROID='google-services.json'
GOOGLE_SERVICES_IOS='GoogleService-Info.plist'
TARGET_FILE='ApiKeys.js'
ANDROID_GOOGLE_SERVICES_PATH='android/app'
IOS_GOOGLE_SERVICES_PATH='android/app'
API_KEYS_PATH='src/config'
ENVIROMENT="dev"

for arg in "${ARGS[@]}"
do
  case "$arg" in
    "--prod")
      ENVIROMENT="prod"
      ;;
    "prod")
      ENVIROMENT="prod"
      ;;
    "--staging")
      ENVIROMENT="staging"
      ;;
    "staging")
      ENVIROMENT="staging"
      ;;
    "list")
      ENVIROMENT="list"
      ;;
    "--list")
      ENVIROMENT="list"
      ;;
  esac
done

case "$ENVIROMENT" in
  "prod")
    echo "=====> Switching to Firebase Production Environment"
    yes | cp -rf $ENV_PATH/$ENVIROMENT/$GOOGLE_SERVICES_ANDROID $ANDROID_GOOGLE_SERVICES_PATH
    yes | cp -rf $ENV_PATH/$ENVIROMENT/$GOOGLE_SERVICES_IOS $ANDROID_GOOGLE_SERVICES_PATH
    yes | cp -rf $ENV_PATH/$ENVIROMENT/$TARGET_FILE $API_KEYS_PATH
    echo "=====> Switch success"
    ;;
  "staging")
    echo "=====> Switching to Firebase Staging Environment"
    yes | cp -rf $ENV_PATH/$ENVIROMENT/$GOOGLE_SERVICES_ANDROID $ANDROID_GOOGLE_SERVICES_PATH
    yes | cp -rf $ENV_PATH/$ENVIROMENT/$GOOGLE_SERVICES_IOS $ANDROID_GOOGLE_SERVICES_PATH
    yes | cp -rf $ENV_PATH/$ENVIROMENT/$TARGET_FILE $API_KEYS_PATH
    echo "=====> Switch success"
    ;;
  "dev")
    echo "=====> Switching to Firebase Dev Environment"
    yes | cp -rf $ENV_PATH/$ENVIROMENT/$GOOGLE_SERVICES_ANDROID $ANDROID_GOOGLE_SERVICES_PATH
    yes | cp -rf $ENV_PATH/$ENVIROMENT/$GOOGLE_SERVICES_IOS $ANDROID_GOOGLE_SERVICES_PATH
    yes | cp -rf $ENV_PATH/$ENVIROMENT/$TARGET_FILE $API_KEYS_PATH
    echo "=====> Switch success"
    ;;
  "list")
    echo "\n===== Available Environments =====\n"
    echo "No.\tEnviroment"
    echo "1\tprod, production"
    echo "2\tdev, development"
    echo "3\tstaging"
    echo "\n"
    ;;
  *)
    echo "Run ‘sh setenv list or ./setenv list’ to list available environments."
esac
